### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by mike-sirs** [arkhitech/redmine_timesheet_plugin#27]
Hello
i got 414 error by press CSV export

link looks like
"http://localhost/timesheet/report.csv?timesheet%5Bactivities%5D%5B%5D=9&timesheet%5Bactivities%5D%5B%5D=24&timesheet%5Bactivities%5D%5B%5D=31&timesheet%5Bactivities%5D%5B%5D=40&timesheet%5Bactivities%5D%5B%5D=51&timesheet%5Bactivities%5D%5B%5D=61&timesheet%5Bactivities%5D%5B%5D=71&timesheet%5Bactivities%5D%5B%5D=81&timesheet%5Bactivities%5D%5B%5D=91&timesheet%5Bactivities%5D%5B%5D=101&timesheet%5Bactivities%5D%5B%5D=110&timesheet%5Bactivities%5D%5B%5D=250&timesheet%5Bactivities%5D%5B%5D=278&timesheet%5Bactivities%5D%5B%5D=834&timesheet%5Bactivities...... more then 1024*10

redmine 2.2.3

can you help me?

**Comment by Shruthiss** [comment]
Hello 
I am getting error when I click on csv link.Error is "Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server".
Please help me

**Comment by undead-osiris** [comment]
hey, you can try it 'https://github.com/undead-osiris/redmine_timesheet_plugin.git'
i have added check box 'Generate report for download'

**Comment by Shruthiss** [comment]
Actually this plugin was working fine.But recently users increased.So is it because of more users entering timesheet?
